FORMAT: 1A
HOST: https://api.bungomail.com/v0

# 青空文庫API - ZORAPI（ゾラピ）
青空文庫の作品データを検索できる非公式APIです。

取得できるすべてのデータはスプレッドシートで公開しているので、何ならこのシートをダウンロードしてご自由にお使いください。
https://docs.google.com/spreadsheets/d/1n04e6POI04TBt-3HJUH10-T5cxhPZHcBWmFA4tSHjqE/edit?usp=sharing

# Group Books
作品情報API

## 作品検索 [GET /books?作品名={%E4%BD%9C%E5%93%81%E5%90%8D}&limit={limit}&after={after}]
検索条件に合致する作品を配列で返します。
検索可能なカラムは、スプレッドシートでオレンジ色になっているカラムです。

+ Parameters
    + %E4%BD%9C%E5%93%81%E5%90%8D: `走れメロス` (string, optional) - 検索対象カラムを指定して、完全一致で検索できます。また「作品名」カラムのみ`作品名=/走れ/`とすることでLIKE検索可能です。
    + limit: 10 (integer, optional) - 取得件数（max50）
    + after: `100,10` (string, optional) - ページングは、after または beforeで「累計アクセス数, 作品ID」のオフセットを指定。Responseにこの値が付与されたlinksが返ってくるので、手動で計算する必要はありません。

+ Request (plain/text)

+ Response 200 (application/json)
    + Attributes
        + books: `true` (boolean) - 登録結果
        + links: `oskamathis` (string) - ユーザ名


## 作品データ取得 [GET /books/{id}]
作品IDで指定した作品のデータを取得します。

+ Parameters
    + id: 10 (integer) - 作品ID

+ Request (plain/text)

+ Response 200 (application/json)
    + Attributes
        + result: `true` (boolean) - 登録結果
        + name: `oskamathis` (string) - ユーザ名
        + email: `oskamathis@gmail.com` (string) - メールアドレス
        + message: `User creation succeeded.` (string) - 登録メッセージ


# Group Persons
人物情報API

## 人物検索 [GET /persons]
検索条件に合致する人物情報を配列で返します。

+ Request (application/json)
    + Attributes
        + name: `oskamathis` (string, required) - ユーザ名
        + email: `oskamathis@gmail.com` (string, required) - メールアドレス
        + password: `1xU35jQy` (string, required) - パスワード

+ Response 200 (application/json)
    + Attributes
        + result: `true` (boolean) - 登録結果
        + name: `oskamathis` (string) - ユーザ名
        + email: `oskamathis@gmail.com` (string) - メールアドレス
        + message: `User creation succeeded.` (string) - 登録メッセージ


## 人物データ取得 [GET /persons/:id]
人物IDで指定した人物のデータを取得します。

+ Request (application/json)
    + Attributes
        + name: `oskamathis` (string, required) - ユーザ名
        + email: `oskamathis@gmail.com` (string, required) - メールアドレス
        + password: `1xU35jQy` (string, required) - パスワード

+ Response 200 (application/json)
    + Attributes
        + result: `true` (boolean) - 登録結果
        + name: `oskamathis` (string) - ユーザ名
        + email: `oskamathis@gmail.com` (string) - メールアドレス
        + message: `User creation succeeded.` (string) - 登録メッセージ
